version: 2.1

orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout # this pulls code down from GitHub
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results