version: 2.0


jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: sudo chmod +x ./mvnw package