version: 2.1

jobs:
  build:
    docker:
      - image circleci/openjdk:11.0.3-jdk-stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
